/*

Filename: cursor_tiles.c 

Tile Source File

Info:
 Form                 : All tiles as one unit
 Format               : Gameboy 4 color
 Compression          : None
 Counter              : None
 Tile size            : 8 x 8
 Tiles                : 0 to 1

 Convert to metatiles : No

 This file was generated by: Gimp Tilemap Plugin

*/


/*
// Optional CGB Palette

const unsigned int cursor_pal_cgb[5] = {
  0x4358,0x2B31,0x1585,0x04E2,  // Palette 0 
  0x0000,};
*/

/*
// Optional Per-tile CGB Pal number for SMS/GG Compatibility mode

const unsigned char cursor_tiles_pals[] = {
 0x00,
};

*/

// Start of Tile data

const unsigned char cursor_tiles[] = {
 0xF8, 0xF8, 0xE0, 0xE0, 0xF0, 0xF0, 0xB8, 0xB8,
 0x9C, 0x9C, 0x0E, 0x0E, 0x06, 0x06, 0x00, 0x00,


};
