/*

Filename: empty_square_tiles.c 

Tile Source File

Info:
 Form                 : All tiles as one unit
 Format               : Gameboy 4 color
 Compression          : None
 Counter              : None
 Tile size            : 8 x 8
 Tiles                : 0 to 1

 Convert to metatiles : No

 This file was generated by: Gimp Tilemap Plugin

*/

const unsigned char empty_square_tiles[] = {
 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,


};