/*

Filename: empty_square_map.c 

Map SOURCE File 

 Info:
   Section       :
   Bank          : 0
   Map size      : 3 x 3
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define empty_square_map_width 3
#define empty_square_map_height 3
#define empty_square_map_tiles 9
#define empty_square_map_bytes 9


const unsigned char empty_square_map[9] = 
{
   0,   0,   0,   0,   0,   0,   0,   0,   0, };