/*

Filename: game_background_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define game_background_map_width 20
#define game_background_map_height 18
#define game_background_map_tiles 360
#define game_background_map_bytes 360

extern unsigned char game_background_map[];