/*

Filename: symbol_o_map.c 

Map SOURCE File 

 Info:
   Section       :
   Bank          : 0
   Map size      : 3 x 3
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define symbol_o_map_width 3
#define symbol_o_map_height 3
#define symbol_o_map_tiles 9
#define symbol_o_map_bytes 9


const unsigned char symbol_o_map[9] = 
{
   0,   1,   2,   3,   4,   5,   2,   6,   0, };